[workspace]
members = [
    "src-tauri"
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.77"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
